main: "com.activation.premium.ActivationPremium"
name: "Activation-Premium"
version: "1.0"
api-version: "1.20"

libraries:
  - "io.github.monun:invfx-core:3.3.2"
  - "org.jetbrains.kotlin:kotlin-stdlib:1.9.21"

commands:
  home:
    usage: "/<command>"
  visit:
    usage: "/<command> [player]"
